name: Push CI/CD Production

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: yarn install
        env:
          CI: 'true'
        run: yarn install

      - name: yarn test
        env:
          CI: 'true'
          NODE_ENV: 'production'
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL_STAGING }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY_STAGING }}
        run: yarn test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_AUGORA_ORGID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECTID_OVERSEER }}
          github-comment: false
          vercel-args: --prod --force --skip-domain
          vercel-version: '34.3.0'
          alias-domains: |
            backoffice.augora.fr
